dist: xenial
language: python
python: 3.7.2
install:
  - pip install --upgrade pip
  - pip install -U -r requirements.txt
  - pip install prophet
  - pip install -e .      # installs your package as a wheel into Travis’s virtual environment.
script:
  - pytest --cov=easyprophet
after_success:
  — coveralls